export const FETCH_RESTAURNATS = 'FETCH_RESTAURNATS';
export const FETCH_RESTAURNATS_SUCCESS = 'FETCH_RESTAURNATS_SUCCESS';
export const LOADING = 'LOADING';
export const FETCH_RESTAURNATS_FAILED = 'FETCH_RESTAURNATS_FAILED';